# Generated by Django 6.1 on 2026-08-18 10:07

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
